export const profiles = [
  {
    id: 101,
    name: "Eric R West",
    position: "CEO",
    url: "https://www.linkedin.com/in/ericrwest/",
    is_scrape_posts: true,
    is_scrape_comments: true,
    is_scrape_reactions: true,
  },
  {
    id: 102,
    name: "Sophia J Carter",
    position: "CTO",
    url: "https://www.linkedin.com/in/sophiajcarter/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 103,
    name: "Michael D Thompson",
    position: "CFO",
    url: "https://www.linkedin.com/in/michaeldthompson/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 104,
    name: "Emily A Johnson",
    position: "Head of Marketing",
    url: "https://www.linkedin.com/in/emilyajohnson/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 105,
    name: "James L Brown",
    position: "Lead Developer",
    url: "https://www.linkedin.com/in/jameslbrown/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 106,
    name: "Olivia M Green",
    position: "UX Designer",
    url: "https://www.linkedin.com/in/oliviamgreen/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 107,
    name: "David S White",
    position: "Product Manager",
    url: "https://www.linkedin.com/in/davidswhite/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 108,
    name: "Isabella K Moore",
    position: "Data Scientist",
    url: "https://www.linkedin.com/in/isabellakmoore/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 109,
    name: "Ethan R Taylor",
    position: "QA Engineer",
    url: "https://www.linkedin.com/in/ethanrtaylor/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 110,
    name: "Charlotte H Lee",
    position: "HR Specialist",
    url: "https://www.linkedin.com/in/charlottehlee/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 111,
    name: "Henry C Adams",
    position: "Backend Developer",
    url: "https://www.linkedin.com/in/henrycadams/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 112,
    name: "Mia P Scott",
    position: "Frontend Developer",
    url: "https://www.linkedin.com/in/miapscott/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 113,
    name: "Alexander J Brown",
    position: "Cloud Engineer",
    url: "https://www.linkedin.com/in/alexanderjbrown/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 114,
    name: "Ella K Harris",
    position: "Cybersecurity Analyst",
    url: "https://www.linkedin.com/in/ellakharris/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 115,
    name: "Daniel M Walker",
    position: "DevOps Engineer",
    url: "https://www.linkedin.com/in/danielmwalker/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 116,
    name: "Ava R Robinson",
    position: "Project Coordinator",
    url: "https://www.linkedin.com/in/avarrobinson/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 117,
    name: "Noah W Turner",
    position: "Business Analyst",
    url: "https://www.linkedin.com/in/noahwturner/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 118,
    name: "Grace H Carter",
    position: "SEO Specialist",
    url: "https://www.linkedin.com/in/gracehcarter/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 119,
    name: "Lucas T Parker",
    position: "Mobile App Developer",
    url: "https://www.linkedin.com/in/lucastparker/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 120,
    name: "Lily B Collins",
    position: "Graphic Designer",
    url: "https://www.linkedin.com/in/lilybcollins/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 121,
    name: "William E Brooks",
    position: "Sales Manager",
    url: "https://www.linkedin.com/in/williamebrooks/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 122,
    name: "Zoe M Bennett",
    position: "Content Writer",
    url: "https://www.linkedin.com/in/zoembennett/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 123,
    name: "Benjamin C Morgan",
    position: "Software Architect",
    url: "https://www.linkedin.com/in/benjamincmorgan/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 124,
    name: "Madison K Reed",
    position: "Digital Marketer",
    url: "https://www.linkedin.com/in/madisonkreed/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 125,
    name: "Elijah R Foster",
    position: "Operations Manager",
    url: "https://www.linkedin.com/in/elijahrfoster/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 126,
    name: "Scarlett A Price",
    position: "E-commerce Specialist",
    url: "https://www.linkedin.com/in/scarlettaprice/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 127,
    name: "Logan D Hill",
    position: "AI Researcher",
    url: "https://www.linkedin.com/in/logandhill/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 128,
    name: "Harper T Cooper",
    position: "Technical Writer",
    url: "https://www.linkedin.com/in/harpertcooper/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 129,
    name: "Jack F Mitchell",
    position: "Scrum Master",
    url: "https://www.linkedin.com/in/jackfmitchell/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
  {
    id: 130,
    name: "Sofia L Phillips",
    position: "Full Stack Developer",
    url: "https://www.linkedin.com/in/sofialphillips/",
    is_scrape_posts: false,
    is_scrape_comments: false,
    is_scrape_reactions: false,
  },
];
